import { AtividadeAgricola } from "../types/atividade";

/** Lista de responsáveis usada enquanto o cadastro de funcionários não existe */
export const FUNCIONARIOS_MOCK = [
  { id: 1, nome: "João Silva", cargo: "Operador de Máquinas" },
  { id: 2, nome: "Maria Souza", cargo: "Técnica Agrícola" },
  { id: 3, nome: "Carlos Lima", cargo: "Encarregado de Campo" },
  { id: 4, nome: "Ana Ferreira", cargo: "Agrônoma" },
  { id: 5, nome: "Pedro Rocha", cargo: "Tratorista" },
];

export const MAQUINAS_MOCK = [
  "Trator John Deere 6110J",
  "Trator Massey Ferguson 7180",
  "Colheitadeira New Holland CR",
  "Pulverizador Autopropelido Jacto",
  "Grade Aradora 20 discos",
  "Subsolador 7 hastes",
  "Plantadeira Semeato 15 linhas",
  "Distribuidor de Calcário",
  "Pivô Central Valley",
];

export const INSUMOS_MOCK = [
  { nome: "Semente de Soja BMX", unidade: "kg" },
  { nome: "Ureia 45%", unidade: "kg" },
  { nome: "MAP 11-52-00", unidade: "kg" },
  { nome: "Calcário Dolomítico", unidade: "t" },
  { nome: "Gesso Agrícola", unidade: "t" },
  { nome: "Glifosato 480", unidade: "L" },
  { nome: "Fungicida Triazol", unidade: "L" },
  { nome: "Óleo Diesel S10", unidade: "L" },
];

/**
 * Dados de demonstração usados enquanto o endpoint /api/atividades não responde.
 */
export const ATIVIDADES_MOCK: AtividadeAgricola[] = [
  {
    id: "a-001",
    id_empresa: 1,
    id_propriedade: 1,
    nome_propriedade: "Fazenda Santa Helena",
    id_talhao: "t-001",
    codigo_talhao: "TLH-001",
    nome_talhao: "Talhão Boa Vista",
    id_safra: "s-2425",
    safra: "2024/2025",
    tipo_atividade: "Pulverização",
    data_inicio: "2025-01-08",
    data_fim: "2025-01-09",
    id_responsavel: 1,
    responsavel: "João Silva",
    status: "Concluída",
    custo_operacao: 18400,
    insumos: [
      { nome: "Fungicida Triazol", quantidade: 320, unidade: "L", custo: 12800 },
      { nome: "Óleo Diesel S10", quantidade: 180, unidade: "L", custo: 1080 },
    ],
    maquinas: [{ nome: "Pulverizador Autopropelido Jacto", horas: 14, custo: 4520 }],
    observacoes: "Aplicação preventiva de ferrugem asiática.",
  },
  {
    id: "a-002",
    id_empresa: 1,
    id_propriedade: 1,
    nome_propriedade: "Fazenda Santa Helena",
    id_talhao: "t-002",
    codigo_talhao: "TLH-002",
    nome_talhao: "Talhão Corredeira",
    id_safra: "s-2425",
    safra: "2024/2025",
    tipo_atividade: "Adubação",
    data_inicio: "2025-01-20",
    data_fim: "2025-01-24",
    id_responsavel: 2,
    responsavel: "Maria Souza",
    status: "Em Andamento",
    custo_operacao: 42600,
    insumos: [{ nome: "Ureia 45%", quantidade: 9000, unidade: "kg", custo: 36000 }],
    maquinas: [{ nome: "Trator John Deere 6110J", horas: 22, custo: 6600 }],
    observacoes: "Adubação de cobertura conforme análise de solo.",
  },
  {
    id: "a-003",
    id_empresa: 1,
    id_propriedade: 2,
    nome_propriedade: "Fazenda Rio Verde",
    id_talhao: "t-003",
    codigo_talhao: "TLH-003",
    nome_talhao: "Talhão Barra Nova",
    id_safra: "s-2425",
    safra: "2024/2025",
    tipo_atividade: "Plantio Direto",
    data_inicio: "2025-10-05",
    data_fim: "2025-10-12",
    id_responsavel: 3,
    responsavel: "Carlos Lima",
    status: "Planejada",
    custo_operacao: 96500,
    insumos: [{ nome: "Semente de Soja BMX", quantidade: 12000, unidade: "kg", custo: 84000 }],
    maquinas: [{ nome: "Plantadeira Semeato 15 linhas", horas: 40, custo: 12500 }],
  },
  {
    id: "a-004",
    id_empresa: 1,
    id_propriedade: 1,
    nome_propriedade: "Fazenda Santa Helena",
    id_talhao: "t-001",
    codigo_talhao: "TLH-001",
    nome_talhao: "Talhão Boa Vista",
    id_safra: "s-2324",
    safra: "2023/2024",
    tipo_atividade: "Calagem",
    data_inicio: "2024-07-02",
    data_fim: "2024-07-08",
    id_responsavel: 4,
    responsavel: "Ana Ferreira",
    status: "Concluída",
    custo_operacao: 31200,
    insumos: [{ nome: "Calcário Dolomítico", quantidade: 340, unidade: "t", custo: 25500 }],
    maquinas: [{ nome: "Distribuidor de Calcário", horas: 30, custo: 5700 }],
  },
  {
    id: "a-005",
    id_empresa: 1,
    id_propriedade: 2,
    nome_propriedade: "Fazenda Rio Verde",
    id_talhao: "t-004",
    codigo_talhao: "TLH-004",
    nome_talhao: "Talhão Pedra Alta",
    id_safra: "s-2324",
    safra: "2023/2024",
    tipo_atividade: "Gradagem",
    data_inicio: "2024-08-14",
    data_fim: "2024-08-16",
    id_responsavel: 5,
    responsavel: "Pedro Rocha",
    status: "Concluída",
    custo_operacao: 14300,
    maquinas: [{ nome: "Grade Aradora 20 discos", horas: 18, custo: 14300 }],
  },
  {
    id: "a-006",
    id_empresa: 1,
    id_propriedade: 2,
    nome_propriedade: "Fazenda Rio Verde",
    id_talhao: "t-003",
    codigo_talhao: "TLH-003",
    nome_talhao: "Talhão Barra Nova",
    id_safra: "s-2425",
    safra: "2024/2025",
    tipo_atividade: "Irrigação Programada",
    data_inicio: "2025-02-01",
    data_fim: "2025-02-28",
    id_responsavel: 2,
    responsavel: "Maria Souza",
    status: "Em Andamento",
    custo_operacao: 9800,
    maquinas: [{ nome: "Pivô Central Valley", horas: 210, custo: 9800 }],
  },
  {
    id: "a-007",
    id_empresa: 1,
    id_propriedade: 1,
    nome_propriedade: "Fazenda Santa Helena",
    id_talhao: "t-002",
    codigo_talhao: "TLH-002",
    nome_talhao: "Talhão Corredeira",
    id_safra: "s-2425",
    safra: "2024/2025",
    tipo_atividade: "Colheita Mecanizada",
    data_inicio: "2025-03-01",
    data_fim: "2025-03-15",
    id_responsavel: 1,
    responsavel: "João Silva",
    status: "Planejada",
    custo_operacao: 58700,
    maquinas: [{ nome: "Colheitadeira New Holland CR", horas: 96, custo: 58700 }],
  },
  {
    id: "a-008",
    id_empresa: 1,
    id_propriedade: 1,
    nome_propriedade: "Fazenda Santa Helena",
    id_talhao: "t-001",
    codigo_talhao: "TLH-001",
    nome_talhao: "Talhão Boa Vista",
    id_safra: "s-2425",
    safra: "2024/2025",
    tipo_atividade: "Subsolagem",
    data_inicio: "2025-06-10",
    data_fim: "2025-06-14",
    id_responsavel: 5,
    responsavel: "Pedro Rocha",
    status: "Em Andamento",
    custo_operacao: 21900,
    maquinas: [{ nome: "Subsolador 7 hastes", horas: 26, custo: 21900 }],
    observacoes: "Rompimento de camada compactada identificada na amostragem.",
  },
  {
    id: "a-009",
    id_empresa: 1,
    id_propriedade: 2,
    nome_propriedade: "Fazenda Rio Verde",
    id_talhao: "t-004",
    codigo_talhao: "TLH-004",
    nome_talhao: "Talhão Pedra Alta",
    id_safra: "s-2526",
    safra: "2025/2026",
    tipo_atividade: "Gessagem",
    data_inicio: "2026-07-05",
    data_fim: "2026-07-11",
    id_responsavel: 4,
    responsavel: "Ana Ferreira",
    status: "Planejada",
    custo_operacao: 17600,
    insumos: [{ nome: "Gesso Agrícola", quantidade: 210, unidade: "t", custo: 14700 }],
  },
  {
    id: "a-010",
    id_empresa: 1,
    id_propriedade: 1,
    nome_propriedade: "Fazenda Santa Helena",
    id_talhao: "t-002",
    codigo_talhao: "TLH-002",
    nome_talhao: "Talhão Corredeira",
    id_safra: "s-2526",
    safra: "2025/2026",
    tipo_atividade: "Aração",
    data_inicio: "2026-08-03",
    data_fim: "2026-08-07",
    id_responsavel: 3,
    responsavel: "Carlos Lima",
    status: "Em Andamento",
    custo_operacao: 12400,
    maquinas: [{ nome: "Trator Massey Ferguson 7180", horas: 20, custo: 12400 }],
  },
  {
    id: "a-011",
    id_empresa: 1,
    id_propriedade: 2,
    nome_propriedade: "Fazenda Rio Verde",
    id_talhao: "t-003",
    codigo_talhao: "TLH-003",
    nome_talhao: "Talhão Barra Nova",
    id_safra: "s-2526",
    safra: "2025/2026",
    tipo_atividade: "Nivelamento",
    data_inicio: "2026-09-01",
    data_fim: "2026-09-04",
    id_responsavel: 5,
    responsavel: "Pedro Rocha",
    status: "Planejada",
    custo_operacao: 8300,
  },
  {
    id: "a-012",
    id_empresa: 1,
    id_propriedade: 1,
    nome_propriedade: "Fazenda Santa Helena",
    id_talhao: "t-001",
    codigo_talhao: "TLH-001",
    nome_talhao: "Talhão Boa Vista",
    id_safra: "s-2526",
    safra: "2025/2026",
    tipo_atividade: "Irrigação Emergencial",
    data_inicio: "2026-08-20",
    data_fim: "2026-08-26",
    id_responsavel: 2,
    responsavel: "Maria Souza",
    status: "Planejada",
    custo_operacao: 6400,
    observacoes: "Veranico previsto para a última semana de agosto.",
  },
];
