import { Insumo, MovimentacaoEstoque } from "../types/insumo";

/** Fornecedores usados enquanto o cadastro próprio não existe */
export const FORNECEDORES_MOCK = [
  "Agro Insumos Ltda.",
  "Fertilizantes Centro-Oeste S.A.",
  "Distribuidora Campo Forte",
  "Sementes Boa Safra",
  "Posto Rural Diesel Mais",
  "Vet Center Agropecuária",
];

/**
 * Dados de demonstração usados enquanto o endpoint /api/insumos não responde.
 */
export const INSUMOS_MOCK_ESTOQUE: Insumo[] = [
  {
    id: "i-001",
    nome: "Ureia 45%",
    categoria: "Fertilizantes",
    tipo: "Ureia",
    unidade_medida: "kg",
    fabricante: "Petrobras",
    marca: "Petrofértil",
    fornecedor: "Fertilizantes Centro-Oeste S.A.",
    estoque_atual: 18_500,
    estoque_minimo: 5_000,
    valor_unitario: 4.1,
    status: "Ativo",
    id_propriedade: 1,
    nome_propriedade: "Fazenda Santa Helena",
    observacoes: "Armazenar em local seco e ventilado.",
    lotes: [
      {
        id: "l-001",
        id_insumo: "i-001",
        numero_lote: "UR-2026-014",
        data_fabricacao: "2026-02-10",
        data_validade: "2027-02-10",
        quantidade: 12_000,
      },
      {
        id: "l-002",
        id_insumo: "i-001",
        numero_lote: "UR-2026-021",
        data_fabricacao: "2026-05-04",
        data_validade: "2027-05-04",
        quantidade: 6_500,
      },
    ],
  },
  {
    id: "i-002",
    nome: "MAP 11-52-00",
    categoria: "Fertilizantes",
    tipo: "MAP",
    unidade_medida: "kg",
    fabricante: "Mosaic",
    marca: "Mosaic Fertilizantes",
    fornecedor: "Fertilizantes Centro-Oeste S.A.",
    estoque_atual: 3_200,
    estoque_minimo: 4_000,
    valor_unitario: 5.35,
    status: "Ativo",
    id_propriedade: 1,
    nome_propriedade: "Fazenda Santa Helena",
    lotes: [
      {
        id: "l-003",
        id_insumo: "i-002",
        numero_lote: "MAP-2026-003",
        data_fabricacao: "2026-01-15",
        data_validade: "2027-01-15",
        quantidade: 3_200,
      },
    ],
  },
  {
    id: "i-003",
    nome: "Glifosato 480",
    categoria: "Defensivos Agrícolas",
    tipo: "Herbicida",
    unidade_medida: "L",
    fabricante: "Syngenta",
    marca: "Roundup",
    fornecedor: "Agro Insumos Ltda.",
    estoque_atual: 1_450,
    estoque_minimo: 400,
    valor_unitario: 32.9,
    status: "Ativo",
    id_propriedade: 1,
    nome_propriedade: "Fazenda Santa Helena",
    registro_mapa: "MAPA 04519",
    ficha_tecnica: "Classe toxicológica IV — usar EPI completo.",
    lotes: [
      {
        id: "l-004",
        id_insumo: "i-003",
        numero_lote: "GLI-2025-088",
        data_fabricacao: "2025-08-20",
        data_validade: "2026-09-20",
        quantidade: 650,
      },
      {
        id: "l-005",
        id_insumo: "i-003",
        numero_lote: "GLI-2026-011",
        data_fabricacao: "2026-03-11",
        data_validade: "2028-03-11",
        quantidade: 800,
      },
    ],
  },
  {
    id: "i-004",
    nome: "Fungicida Triazol",
    categoria: "Defensivos Agrícolas",
    tipo: "Fungicida",
    unidade_medida: "L",
    fabricante: "Bayer",
    marca: "Nativo",
    fornecedor: "Agro Insumos Ltda.",
    estoque_atual: 260,
    estoque_minimo: 300,
    valor_unitario: 148.0,
    status: "Ativo",
    id_propriedade: 2,
    nome_propriedade: "Fazenda Rio Verde",
    registro_mapa: "MAPA 01102",
    lotes: [
      {
        id: "l-006",
        id_insumo: "i-004",
        numero_lote: "FUN-2025-042",
        data_fabricacao: "2025-06-02",
        data_validade: "2026-07-02",
        quantidade: 60,
      },
      {
        id: "l-007",
        id_insumo: "i-004",
        numero_lote: "FUN-2026-007",
        data_fabricacao: "2026-04-18",
        data_validade: "2027-10-18",
        quantidade: 200,
      },
    ],
  },
  {
    id: "i-005",
    nome: "Semente de Soja BMX Potência",
    categoria: "Sementes",
    tipo: "Soja",
    unidade_medida: "sc",
    fabricante: "Brasmax",
    marca: "BMX",
    fornecedor: "Sementes Boa Safra",
    estoque_atual: 940,
    estoque_minimo: 200,
    valor_unitario: 620.0,
    status: "Ativo",
    id_propriedade: 2,
    nome_propriedade: "Fazenda Rio Verde",
    lotes: [
      {
        id: "l-008",
        id_insumo: "i-005",
        numero_lote: "SOJ-2026-055",
        data_fabricacao: "2026-06-01",
        data_validade: "2026-10-15",
        quantidade: 940,
      },
    ],
  },
  {
    id: "i-006",
    nome: "Calcário Dolomítico",
    categoria: "Corretivos",
    tipo: "Calcário",
    unidade_medida: "t",
    fabricante: "Mineração Serra Azul",
    marca: "CalSerra",
    fornecedor: "Distribuidora Campo Forte",
    estoque_atual: 320,
    estoque_minimo: 80,
    valor_unitario: 195.0,
    status: "Ativo",
    id_propriedade: 1,
    nome_propriedade: "Fazenda Santa Helena",
  },
  {
    id: "i-007",
    nome: "Óleo Diesel S10",
    categoria: "Combustíveis",
    tipo: "Diesel S10",
    unidade_medida: "L",
    fabricante: "Petrobras",
    marca: "BR",
    fornecedor: "Posto Rural Diesel Mais",
    estoque_atual: 6_800,
    estoque_minimo: 3_000,
    valor_unitario: 6.19,
    status: "Ativo",
    id_propriedade: 1,
    nome_propriedade: "Fazenda Santa Helena",
  },
  {
    id: "i-008",
    nome: "Vacina Aftosa Bovina",
    categoria: "Medicamentos Veterinários",
    tipo: "Vacinas",
    unidade_medida: "dose",
    fabricante: "Zoetis",
    marca: "Aftosan",
    fornecedor: "Vet Center Agropecuária",
    estoque_atual: 480,
    estoque_minimo: 150,
    valor_unitario: 8.4,
    status: "Ativo",
    id_propriedade: 2,
    nome_propriedade: "Fazenda Rio Verde",
    registro_mapa: "MAPA 8821/VET",
    lotes: [
      {
        id: "l-009",
        id_insumo: "i-008",
        numero_lote: "AFT-2026-002",
        data_fabricacao: "2026-03-01",
        data_validade: "2026-09-30",
        quantidade: 480,
      },
    ],
  },
  {
    id: "i-009",
    nome: "Sal Mineral 80P",
    categoria: "Suplementação Animal",
    tipo: "Sal Mineral",
    unidade_medida: "kg",
    fabricante: "Nutripec",
    marca: "Nutripec Bovinos",
    fornecedor: "Distribuidora Campo Forte",
    estoque_atual: 0,
    estoque_minimo: 500,
    valor_unitario: 7.8,
    status: "Ativo",
    id_propriedade: 2,
    nome_propriedade: "Fazenda Rio Verde",
  },
  {
    id: "i-010",
    nome: "Inseticida Piretroide",
    categoria: "Defensivos Agrícolas",
    tipo: "Inseticida",
    unidade_medida: "L",
    fabricante: "FMC",
    marca: "Talisman",
    fornecedor: "Agro Insumos Ltda.",
    estoque_atual: 120,
    estoque_minimo: 100,
    valor_unitario: 96.5,
    status: "Inativo",
    id_propriedade: 1,
    nome_propriedade: "Fazenda Santa Helena",
    observacoes: "Produto descontinuado pelo fabricante.",
    lotes: [
      {
        id: "l-010",
        id_insumo: "i-010",
        numero_lote: "INS-2024-030",
        data_fabricacao: "2024-05-10",
        data_validade: "2026-05-10",
        quantidade: 120,
      },
    ],
  },
];

/**
 * Histórico de movimentações de demonstração (RN005 — rastreabilidade).
 */
export const MOVIMENTACOES_MOCK: MovimentacaoEstoque[] = [
  {
    id: "m-001",
    id_insumo: "i-001",
    nome_insumo: "Ureia 45%",
    tipo: "Entrada",
    quantidade: 20_000,
    valor_unitario: 4.1,
    data_movimentacao: "2026-02-12",
    id_responsavel: 3,
    responsavel: "Carlos Lima",
    fornecedor: "Fertilizantes Centro-Oeste S.A.",
    nota_fiscal: "NF-45821",
    numero_lote: "UR-2026-014",
  },
  {
    id: "m-002",
    id_insumo: "i-001",
    nome_insumo: "Ureia 45%",
    tipo: "Saída",
    quantidade: 9_000,
    valor_unitario: 4.1,
    data_movimentacao: "2026-03-05",
    id_responsavel: 2,
    responsavel: "Maria Souza",
    id_talhao: "t-002",
    codigo_talhao: "TLH-002",
    nome_talhao: "Talhão Corredeira",
    safra: "2025/2026",
    atividade: "Adubação",
    destino: "Adubação de cobertura",
  },
  {
    id: "m-003",
    id_insumo: "i-001",
    nome_insumo: "Ureia 45%",
    tipo: "Entrada",
    quantidade: 7_500,
    valor_unitario: 4.25,
    data_movimentacao: "2026-05-06",
    id_responsavel: 3,
    responsavel: "Carlos Lima",
    fornecedor: "Fertilizantes Centro-Oeste S.A.",
    nota_fiscal: "NF-49110",
    numero_lote: "UR-2026-021",
  },
  {
    id: "m-004",
    id_insumo: "i-003",
    nome_insumo: "Glifosato 480",
    tipo: "Saída",
    quantidade: 380,
    valor_unitario: 32.9,
    data_movimentacao: "2026-04-22",
    id_responsavel: 1,
    responsavel: "João Silva",
    id_talhao: "t-001",
    codigo_talhao: "TLH-001",
    nome_talhao: "Talhão Boa Vista",
    safra: "2025/2026",
    atividade: "Pulverização",
    destino: "Dessecação pré-plantio",
  },
  {
    id: "m-005",
    id_insumo: "i-004",
    nome_insumo: "Fungicida Triazol",
    tipo: "Saída",
    quantidade: 320,
    valor_unitario: 148,
    data_movimentacao: "2026-01-09",
    id_responsavel: 1,
    responsavel: "João Silva",
    id_talhao: "t-001",
    codigo_talhao: "TLH-001",
    nome_talhao: "Talhão Boa Vista",
    safra: "2025/2026",
    atividade: "Pulverização",
    destino: "Controle de ferrugem asiática",
  },
  {
    id: "m-006",
    id_insumo: "i-005",
    nome_insumo: "Semente de Soja BMX Potência",
    tipo: "Entrada",
    quantidade: 1_200,
    valor_unitario: 620,
    data_movimentacao: "2026-06-03",
    id_responsavel: 4,
    responsavel: "Ana Ferreira",
    fornecedor: "Sementes Boa Safra",
    nota_fiscal: "NF-77320",
    numero_lote: "SOJ-2026-055",
  },
  {
    id: "m-007",
    id_insumo: "i-005",
    nome_insumo: "Semente de Soja BMX Potência",
    tipo: "Saída",
    quantidade: 260,
    valor_unitario: 620,
    data_movimentacao: "2026-07-18",
    id_responsavel: 3,
    responsavel: "Carlos Lima",
    id_talhao: "t-003",
    codigo_talhao: "TLH-003",
    nome_talhao: "Talhão Barra Nova",
    safra: "2026/2027",
    atividade: "Plantio Direto",
    destino: "Semeadura de soja",
  },
  {
    id: "m-008",
    id_insumo: "i-006",
    nome_insumo: "Calcário Dolomítico",
    tipo: "Saída",
    quantidade: 140,
    valor_unitario: 195,
    data_movimentacao: "2026-07-04",
    id_responsavel: 4,
    responsavel: "Ana Ferreira",
    id_talhao: "t-001",
    codigo_talhao: "TLH-001",
    nome_talhao: "Talhão Boa Vista",
    safra: "2026/2027",
    atividade: "Calagem",
    destino: "Correção de acidez",
  },
  {
    id: "m-009",
    id_insumo: "i-007",
    nome_insumo: "Óleo Diesel S10",
    tipo: "Entrada",
    quantidade: 10_000,
    valor_unitario: 6.19,
    data_movimentacao: "2026-06-28",
    id_responsavel: 5,
    responsavel: "Pedro Rocha",
    fornecedor: "Posto Rural Diesel Mais",
    nota_fiscal: "NF-10233",
  },
  {
    id: "m-010",
    id_insumo: "i-007",
    nome_insumo: "Óleo Diesel S10",
    tipo: "Saída",
    quantidade: 3_200,
    valor_unitario: 6.19,
    data_movimentacao: "2026-08-02",
    id_responsavel: 5,
    responsavel: "Pedro Rocha",
    id_talhao: "t-002",
    codigo_talhao: "TLH-002",
    nome_talhao: "Talhão Corredeira",
    safra: "2026/2027",
    atividade: "Gradagem",
    destino: "Abastecimento de tratores",
  },
  {
    id: "m-011",
    id_insumo: "i-009",
    nome_insumo: "Sal Mineral 80P",
    tipo: "Saída",
    quantidade: 900,
    valor_unitario: 7.8,
    data_movimentacao: "2026-08-15",
    id_responsavel: 3,
    responsavel: "Carlos Lima",
    safra: "2026/2027",
    destino: "Cocho — pasto Sede",
    observacao: "Saldo zerado, necessário repor.",
  },
  {
    id: "m-012",
    id_insumo: "i-008",
    nome_insumo: "Vacina Aftosa Bovina",
    tipo: "Entrada",
    quantidade: 600,
    valor_unitario: 8.4,
    data_movimentacao: "2026-03-04",
    id_responsavel: 4,
    responsavel: "Ana Ferreira",
    fornecedor: "Vet Center Agropecuária",
    nota_fiscal: "NF-30877",
    numero_lote: "AFT-2026-002",
  },
];
